name: 🔗 Deploy All
on:
  workflow_call:
    inputs:
      build_sha:
        description: "Build commit SHA to use for this job"
        required: true
        type: string
      runner_id:
        description: "Runner ID of the Parent Runner"
        required: true
        type: string
      monoglue-build:
        description: "Build Status"
        required: true
        type: string
      windows-build:
        description: "Build Status"
        required: true
        type: string
      macos-build:
        description: "Build Status"
        required: true
        type: string
      linux-build:
        description: "Build Status"
        required: true
        type: string
      android-build:
        description: "Build Status"
        required: true
        type: string
      ios-build:
        description: "Build Status"
        required: true
        type: string
      new_major:
        description: "New Major # for Version"
        required: true
        type: string
      new_minor:
        description: "New Minor # for Version"
        required: true
        type: string
      new_patch:
        description: "New Patch # for Version"
        required: true
        type: string
      new_version:
        description: "New Version that'll be Deployed"
        required: true
        type: string

env:
  BASE_NAME: Blazium_v
  GODOT_BASE_BRANCH: blazium-dev

concurrency:
  group: ci-${{ github.actor }}-${{ github.event.client_payload.type || 'nightly' }}-deploy-all
  cancel-in-progress: true

jobs:

  template-deploy:
    name: 📊 Template Deploy
    if: contains(github.event.client_payload.deploy, 'templates')
    uses: ./.github/workflows/template_deploy.yml
    secrets: inherit
    with:
      build_sha: ${{ inputs.build_sha }}
      runner_id: ${{ inputs.runner_id }}
      new_version: ${{ inputs.new_version }}
      monoglue-build: ${{ inputs.monoglue-build }}
      windows-build: ${{ inputs.windows-build }}
      macos-build: ${{ inputs.macos-build }}
      linux-build: ${{ inputs.linux-build }}
      android-build: ${{ inputs.android-build }}
      ios-build: ${{ inputs.ios-build }}


  editor-deploy:
    name: 📊 Editor Deploy
    if: contains(github.event.client_payload.deploy, 'editors')
    uses: ./.github/workflows/editor_deploy.yml
    secrets: inherit
    with:
      build_sha: ${{ inputs.build_sha }}
      runner_id: ${{ inputs.runner_id }}
      new_version: ${{ inputs.new_version }}
      monoglue-build: ${{ inputs.monoglue-build }}
      windows-build: ${{ inputs.windows-build }}
      macos-build: ${{ inputs.macos-build }}
      linux-build: ${{ inputs.linux-build }}
      android-build: ${{ inputs.android-build }}